### ISSUE TITLE
Question about Implementation

### ISSUE THREAD

**Issue by Rechi86** [TiagoSilvaPereira/simple-3d-fps#1]
First of all thank, you for sharing this implementation. Coming from Unity this is a very good example of implementing a similar base structure within BJS.
I hope It is ok to ask a question using the issue section.

Within your Game.js: startRenderLoop-Method (line 194), you have a 50ms timeout set. 

```
    startRenderLoop() {
        setTimeout(() => {
            this.engine.runRenderLoop(() => {
                this.currentLevel.scene.render();
            });
        }, 50);
    }
```

I'm not sure why this is needed, but in my own implementation adding a similar timeout solved the Error of "Active camera not set" when disposing the old scene after loading a new one. Is this also the reason you need this timeout? Do you know why this may be needed before disposing the old scene?

**Comment by TiagoSilvaPereira** [comment]
Hi @Rechi86 this timeout is not necessary... I was trying to debug an error and I forgot to remove It... Thank you by notice It, I will remove in a previous commit.

**Comment by TiagoSilvaPereira** [comment]
The "active camera not set" can happen when you don't have an active camera on your scene:

scene.activeCamera = camera;

It is necessary in some places of the application.

**Comment by TiagoSilvaPereira** [comment]
I think the current code I'm using to dispose the scene can help you too: https://github.com/TiagoSilvaPereira/simple-3d-fps/blob/master/src/base/Level.js#L68
